version: '3.8'

services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-ml-model:latest
    container_name: my-ml-container
    ports:
      - "5000:5000"
    environment:
      - ENV=production
      - MODEL_PATH=/app/models/model.joblib
    volumes:
      - ./models:/app/models  # Mount the host's models directory to the container
    restart: unless-stopped

volumes:
  models-data:
